---
name: Delete Obsolete GHCR Images
on:
  schedule:
    - cron: "0 1 * * *"  # every day at midnight
  workflow_dispatch:

permissions:
  contents: read
jobs:
  trigger:
    uses: statnett/github-workflows/.github/workflows/clean-ghcr.yaml@37834049d33c16b2756f90144f3736da4d596ff8 # main
    secrets: inherit
    permissions:
      packages: write
