---
name: Delete Obsolete GHCR Images
on:
  schedule:
    - cron: "0 1 * * *"  # every day at midnight
  workflow_dispatch:

permissions:
  contents: read
jobs:
  trigger:
    uses: statnett/github-workflows/.github/workflows/clean-ghcr.yaml@cd4e825f752b2c4c0909ad977ea8fdd96b6a9528 # main
    secrets: inherit
    permissions:
      packages: write
