---
name: Lint PR
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read
jobs:
  trigger:
    uses: statnett/github-workflows/.github/workflows/lint-pr.yaml@e6814bd0c39d968bfd896cc5ae6de46fb055388e # main
    permissions:
      pull-requests: write
      statuses: write
