---
name: Lint PR
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read
jobs:
  trigger:
    uses: statnett/github-workflows/.github/workflows/lint-pr.yaml@d73574cafc9f815a9c5a0d876d9fa9590c72c5f9 # main
    permissions:
      pull-requests: write
      statuses: write
