---
name: Lint PR
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read
jobs:
  trigger:
    uses: statnett/github-workflows/.github/workflows/lint-pr.yaml@6ce3527760dcc33748ece0e44af291f00f84bacd # main
    permissions:
      pull-requests: write
      statuses: write
