---
name: Release Please
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
jobs:
  trigger:
    uses: statnett/github-workflows/.github/workflows/release-please.yaml@6ce3527760dcc33748ece0e44af291f00f84bacd # main
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
