---
name: Release Please
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
jobs:
  trigger:
    uses: statnett/github-workflows/.github/workflows/release-please.yaml@42b657ebf74160507fdab018895ca57653b7a740 # main
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
