---
name: Release Please
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
jobs:
  trigger:
    uses: statnett/github-workflows/.github/workflows/release-please.yaml@37834049d33c16b2756f90144f3736da4d596ff8 # main
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
