---
name: Scorecard supply-chain security
on:
  branch_protection_rule:
  schedule:
    - cron: "20 7 * * 2"
  push:
    branches:
      - main

permissions:
  contents: read
jobs:
  trigger:
    uses: statnett/github-workflows/.github/workflows/scorecard.yaml@041e38de5cf534e88a865c4d9ebdaf71e2ce19ea # main
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
