---
name: Scorecard supply-chain security
on:
  branch_protection_rule:
  schedule:
    - cron: "20 7 * * 2"
  push:
    branches:
      - main

permissions:
  contents: read
jobs:
  trigger:
    uses: statnett/github-workflows/.github/workflows/scorecard.yaml@206032886cd31cebee1e60f3b18eb7da3d5652cb # main
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
