---
name: Scorecard supply-chain security
on:
  branch_protection_rule:
  schedule:
    - cron: "20 7 * * 2"
  push:
    branches:
      - main

permissions:
  contents: read
jobs:
  trigger:
    uses: statnett/github-workflows/.github/workflows/scorecard.yaml@6d4a134582c00edf0d1dfc1b297c4b8aeb775702 # main
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
